
codes = {'atn': 'AaltenPoort',
         'ac': 'Abcoude',
         'akm': 'Akkrum',
         'amr': 'Alkmaar',
         'amrn': 'Alkmaar Noord',
         'aml': 'Almelo',
         'amri': 'Almelo de Riet',
         'almb': 'Almere Buiten',
         'alm': 'Almere Centrum',
         'almm': 'Almere Muziekwijk',
         'almo': 'Almere Oostvaarders',
         'almp': 'Almere Parkwijk',
         'ampo': 'Almere Poort',
         'apn': 'Alphen aan den Rijn',
         'amf': 'Amersfoort',
         'amfs': 'Amersfoort Schothorst',
         'avat': 'Amersfoort Vathorst',
         'asa': 'Amsterdam Amstel',
         'asdar': 'Amsterdam ArenA',
         'asb': 'Amsterdam Bijlmer ArenA',
         'asd': 'Amsterdam Centraal',
         'asdh': 'Amsterdam Holendrecht',
         'asdl': 'Amsterdam Lelylaan',
         'asdm': 'Amsterdam Muiderpoort',
         'rai': 'Amsterdam RAI',
         'assp': 'Amsterdam Science Park',
         'ass': 'Amsterdam Sloterdijk',
         'asdz': 'Amsterdam Zuid',
         'ana': 'Anna Paulowna',
         'apd': 'Apeldoorn',
         'apdm': 'Apeldoorn De Maten',
         'apdo': 'Apeldoorn Osseveld',
         'apg': 'Appingedam',
         'akl': 'Arkel',
         'arn': 'Arnemuiden',
         'ah': 'Arnhem Centraal',
         'ahpr': 'Arnhem Presikhaaf',
         'ahp': 'Arnhem Velperpoort',
         'ahz': 'Arnhem Zuid',
         'asn': 'Assen',
         'brn': 'Baarn',
         'bf': 'Baflo',
         'brd': 'Barendrecht',
         'bnc': 'Barneveld Centrum',
         'bnn': 'Barneveld Noord',
         'bdm': 'Bedum',
         'bk': 'Beek-Elsloo',
         'bsd': 'Beesd',
         'bl': 'Beilen',
         'bgn': 'Bergen op Zoom',
         'bet': 'Best',
         'bv': 'Beverwijk',
         'bhv': 'Bilthoven',
         'br': 'Blerick',
         'bll': 'Bloemendaal',
         'bdg': 'Bodegraven',
         'bn': 'Borne',
         'bsk': 'Boskoop',
         'bsks': 'Boskoop Snijdelwijk',
         'bhdv': 'Boven-Hardinxveld',
         'bkf': 'Bovenkarspel Flora',
         'bkg': 'Bovenkarspel-Grootebroek',
         'bmr': 'Boxmeer',
         'btl': 'Boxtel',
         'bd': 'Breda',
         'bdpb': 'Breda-Prinsenbeek',
         'bkl': 'Breukelen',
         'bmn': 'Brummen',
         'bp': 'Buitenpost',
         'bde': 'Bunde',
         'bnk': 'Bunnik',
         'bsmz': 'Bussum Zuid',
         'cps': 'Capelle Schollevaar',
         'cas': 'Castricum',
         'cvm': 'Chevremont',
         'co': 'Coevorden',
         'ck': 'Cuijk',
         'cl': 'Culemborg',
         'da': 'Daarlerveen',
         'dln': 'Dalen',
         'dl': 'Dalfsen',
         'dvnk': 'De Vink',
         'dei': 'Deinum',
         'ddn': 'Delden',
         'dt': 'Delft',
         'dtz': 'Delft Zuid',
         'dz': 'Delfzijl',
         'dzw': 'Delfzijl West',
         'dld': 'Den Dolder',
         'gvc': 'Den Haag Centraal',
         'gv': 'Den Haag HS',
         'laa': 'Den Haag Laan van NOI',
         'gvm': 'Den Haag Mariahoeve',
         'gvmw': 'Den Haag Moerwijk',
         'ypb': 'Den Haag Ypenburg',
         'hdr': 'Den Helder',
         'hdrz': 'Den Helder Zuid',
         'dn': 'Deurne',
         'dv': 'Deventer',
         'dvc': 'Deventer Colmschate',
         'dvt': 'Deventer De Scheg',
         'dwe': 'De Westereen',
         'did': 'Didam',
         'dmn': 'Diemen',
         'dmnz': 'Diemen Zuid',
         'dr': 'Dieren',
         'dtc': 'Doetinchem',
         'dtch': 'Doetinchem De Huet',
         'ddr': 'Dordrecht',
         'ddrs': 'Dordrecht Stadspolders',
         'ddzd': 'Dordrecht Zuid',
         'db': 'Driebergen-Zeist',
         'drh': 'Driehuis',
         'drp': 'Dronryp',
         'dron': 'Dronten',
         'dvn': 'Duiven',
         'dvd': 'Duivendrecht',
         'ec': 'Echt',
         'edc': 'Ede Centrum',
         'ed': 'Ede-Wageningen',
         'eem': 'Eemshaven',
         'edn': 'Eijsden',
         'ehv': 'Eindhoven Centraal',
         'ehs': 'Eindhoven Strijp-S',
         'ehst': 'Eindhoven Stadion',
         'est': 'Elst',
         'emn': 'Emmen',
         'emnz': 'Emmen Zuid',
         'ekz': 'Enkhuizen',
         'es': 'Enschede',
         'ese': 'Enschede De Eschmarke',
         'esk': 'Enschede Kennispark',
         'eml': 'Ermelo',
         'etn': 'Etten-Leur',
         'egh': 'Eygelshoven',
         'eghm': 'Eygelshoven Markt',
         'fwd': 'Feanwâlden',
         'fn': 'Franeker',
         'gdr': 'Gaanderen',
         'gdm': 'Geldermalsen',
         'gp': 'Geldrop',
         'gln': 'Geleen Oost',
         'lut': 'Geleen-Lutterade',
         'gz': 'Gilze-Rijen',
         'gbr': 'Glanerbrug',
         'gs': 'Goes',
         'go': 'Goor',
         'gr': 'Gorinchem',
         'gd': 'Gouda',
         'gdg': 'Gouda Goverwelle',
         'gbg': 'Gramsbergen',
         'gk': 'Grijpskerk',
         'gn': 'Groningen',
         'gerp': 'Groningen Europapark',
         'gnn': 'Groningen Noord',
         'gw': 'Grou-Jirnsum',
         'hlm': 'Haarlem',
         'hlms': 'Haarlem Spaarnwoude',
         'hwzw': 'Halfweg-Zwanenburg',
         'hde': "'t Harde",
         'hdb': 'Hardenberg',
         'hd': 'Harderwijk',
         'hbzm/bzm': 'Hardinxveld Blauwe Zoom',
         'gnd/hag': 'Hardinxveld-Giessendam',
         'hrn': 'Haren',
         'hlg': 'Harlingen',
         'hlgh': 'Harlingen Haven',
         'hk': 'Heemskerk',
         'had': 'Heemstede-Aerdenhout',
         'hr': 'Heerenveen',
         'hry': 'Heerenveen IJsstadion',
         'hwd': 'Heerhugowaard',
         'hrl': 'Heerlen',
         'hrlw': 'Heerlen Woonboulevard',
         'hze': 'Heeze',
         'hlo': 'Heiloo',
         'hno': 'Heino',
         'hm': 'Helmond',
         'hmbv': 'Helmond Brandevoort',
         'hmbh': 'Helmond Brouwhuis',
         'hmh': "Helmond 't Hout",
         'hmn': 'Hemmen-Dodewaard',
         'hgl': 'Hengelo',
         'hglg': 'Hengelo Gezondheidspark',
         'hglo': 'Hengelo Oost',
         'ht': "'s-Hertogenbosch",
         'hto': "'s-Hertogenbosch Oost",
         'hil': 'Hillegom',
         'hvs': 'Hilversum',
         'hvsn': 'Hilversum Noord',
         'hvsp': 'Hilversum Sportpark',
         'hnp': 'Hindeloopen',
         'hb': 'Hoensbroek',
         'hvl': 'Hoevelaken',
         'hor': 'Hollandsche Rading',
         'hon': 'Holten',
         'hfd': 'Hoofddorp',
         'hgv': 'Hoogeveen',
         'hgz': 'Hoogezand-Sappemeer',
         'hks': 'Hoogkarspel',
         'hn': 'Hoorn',
         'hnk': 'Hoorn Kersenboogerd',
         'hrt': 'Horst-Sevenum',
         'htn': 'Houten',
         'htnc': 'Houten Castellum',
         'sgl': 'Houthem-St. Gerlach',
         'hdg': 'Hurdegaryp',
         'ijt': 'IJlst',
         'kpn': 'Kampen',
         'kpnz': 'Kampen Zuid',
         'bzl': 'Kapelle-Biezelinge',
         'krd': 'Kerkrade Centrum',
         'ktr': 'Kesteren',
         'kbk': 'Klarenbeek',
         'kmr': 'Klimmen-Ransdaal',
         'kz': 'Koog aan de Zaan',
         'kmw': 'Koudum-Molkwerum',
         'kbd': 'Krabbendijke',
         'kma': 'Krommenie-Assendelft',
         'kw': 'Kropswolde',
         'krg': 'Kruiningen-Yerseke',
         'zlw': 'Lage Zwaluwe',
         'lg': 'Landgraaf',
         'llzm': 'Lansingerland-Zoetermeer',
         'ldm': 'Leerdam',
         'lw': 'Leeuwarden',
         'lwc': 'Leeuwarden Camminghaburen',
         'ledn': 'Leiden Centraal',
         'ldl': 'Leiden Lammenschans',
         'lls': 'Lelystad Centrum',
         'ltv': 'Lichtenvoorde-Groenlo',
         'lc': 'Lochem',
         'lp': 'Loppersum',
         'ltn': 'Lunteren',
         'mz': 'Maarheeze',
         'mrn': 'Maarn',
         'mas': 'Maarssen',
         'mt': 'Maastricht',
         'mtn': 'Maastricht Noord',
         'mtr': 'Maastricht Randwyck',
         'mg': 'Mantgum',
         'mrb': 'Mariënberg',
         'mth': 'Martenshoek',
         'mes': 'Meerssen',
         'mp': 'Meppel',
         'mdb': 'Middelburg',
         'mmlh': 'Mook-Molenhoek',
         'ndb': 'Naarden-Bussum',
         'na': 'Nieuw Amsterdam',
         'nvp': 'Nieuw Vennep',
         'nwk': 'Nieuwerkerk aan den IJssel',
         'nsch': 'Bad Nieuweschans',
         'nkk': 'Nijkerk',
         'nm': 'Nijmegen',
         'nmd': 'Nijmegen Dukenburg',
         'nmgo': 'Nijmegen Goffert',
         'nmh': 'Nijmegen Heyendaal',
         'nml': 'Nijmegen Lent',
         'nvd': 'Nijverdal',
         'ns': 'Nunspeet',
         'nh': 'Nuth',
         'obd': 'Obdam',
         'ot': 'Oisterwijk',
         'odz': 'Oldenzaal',
         'ost': 'Olst',
         'omn': 'Ommen',
         'otb': 'Oosterbeek',
         'op': 'Opheusden',
         'o': 'Oss',
         'ow': 'Oss West',
         'odb': 'Oudenbosch',
         'ovn': 'Overveen',
         'pmr': 'Purmerend',
         'pmo': 'Purmerend Overwhere',
         'pmw': 'Purmerend Weidevenne',
         'pt': 'Putten',
         'rat': 'Raalte',
         'rvs': 'Ravenstein',
         'rv': 'Reuver',
         'rh': 'Rheden',
         'rhn': 'Rhenen',
         'rsn': 'Rijssen',
         'rsw': 'Rijswijk',
         'rb': 'Rilland-Bath',
         'rm': 'Roermond',
         'rd': 'Roodeschool',
         'rsd': 'Roosendaal',
         'rs': 'Rosmalen',
         'rta': 'Rotterdam Alexander',
         'rtb': 'Rotterdam Blaak',
         'rtd': 'Rotterdam Centraal',
         'rlb': 'Rotterdam Lombardijen',
         'rtn': 'Rotterdam Noord',
         'rtst': 'Rotterdam Stadion',
         'rtz': 'Rotterdam Zuid',
         'rl': 'Ruurlo',
         'sptn': 'Santpoort Noord',
         'sptz': 'Santpoort Zuid',
         'spm': 'Sappemeer Oost',
         'ssh': 'Sassenheim',
         'swd': 'Sauwerd',
         'sgn': 'Schagen',
         'sda': 'Scheemda',
         'sdm': 'Schiedam Centrum',
         'sn': 'Schinnen',
         'sog': 'Schin op Geul',
         'shl': 'Schiphol Airport',
         'std': 'Sittard',
         'sk': 'Sneek',
         'sknd': 'Sneek Noord',
         'st': 'Soest',
         'stz': 'Soest Zuid',
         'sd': 'Soestdijk',
         'sdtb': 'Sliedrecht Baanhoek',
         'sbk': 'Spaubeek',
         'stv': 'Stavoren',
         'stm': 'Stedum',
         'swk': 'Steenwijk',
         'srn': 'Susteren',
         'sm': 'Swalmen',
         'tg': 'Tegelen',
         'tbg': 'Terborg',
         'tl': 'Tiel',
         'tpsw': 'Tiel Passewaaij',
         'tb': 'Tilburg',
         'tbr': 'Tilburg Reeshof',
         'tbu': 'Tilburg Universiteit',
         'twl': 'Twello',
         'utg': 'Uitgeest',
         'uhz': 'Uithuizen',
         'uhm': 'Uithuizermeeden',
         'ust': 'Usquert',
         'ut': 'Utrecht Centraal',
         'utlr': 'Utrecht Leidsche Rijn',
         'utln': 'Utrecht Lunetten',
         'utm': 'Utrecht Maliebaan',
         'uto': 'Utrecht Overvecht',
         'utt': 'Utrecht Terwijde',
         'utvr': 'Utrecht Vaartsche Rijn',
         'utzl': 'Utrecht Zuilen',
         'vk': 'Valkenburg',
         'vsv': 'Varsseveld',
         'vdm': 'Veendam',
         'vndc': 'Veenendaal Centrum',
         'klp': 'Veenendaal-De Klomp',
         'vndw': 'Veenendaal West',
         'vp': 'Velp',
         'vl': 'Venlo',
         'vry': 'Venray',
         'vlb': 'Vierlingsbeek',
         'vtn': 'Vleuten',
         'vs': 'Vlissingen',
         'vss': 'Vlissingen Souburg',
         'vdl': 'Voerendaal',
         'vb': 'Voorburg',
         'vh': 'Voorhout',
         'vst': 'Voorschoten',
         'vem': 'Voorst-Empe',
         'vd': 'Vorden',
         'vz': 'Vriezenveen',
         'vhp': 'Vroomshoop',
         'vg': 'Vught',
         'wad': 'Waddinxveen',
         'wadn': 'Waddinxveen Noord',
         'wadt': 'Waddinxveen Triangel',
         'wfm': 'Warffum',
         'wt': 'Weert',
         'wp': 'Weesp',
         'wl': 'Wehl',
         'wtv': 'Westervoort',
         'wz': 'Wezep',
         'wdn': 'Wierden',
         'wc': 'Wijchen',
         'wh': 'Wijhe',
         'ws': 'Winschoten',
         'wsm': 'Winsum',
         'ww': 'Winterswijk',
         'www': 'Winterswijk West',
         'wd': 'Woerden',
         'wf': 'Wolfheze',
         'wv': 'Wolvega',
         'wk': 'Workum',
         'wm': 'Wormerveer',
         'zd': 'Zaandam',
         'zdk': 'Zaandam Kogerveld',
         'zbm': 'Zaltbommel',
         'zvt': 'Zandvoort aan Zee',
         'za': 'Zetten-Andelst',
         'zv': 'Zevenaar',
         'zvb': 'Zevenbergen',
         'ztm': 'Zoetermeer',
         'ztmo': 'Zoetermeer Oost',
         'zb': 'Zuidbroek',
         'zh': 'Zuidhorn',
         'zp': 'Zutphen',
         'zwd': 'Zwijndrecht',
         'zl': 'Zwolle',
         'zlsh': 'Zwolle Stadshagen',
         'zzs': 'Zaandijk Zaanse Schans'}
